// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIzxBkhWflskro--e60NoXYqHS3w73rl0',
    appId: '1:604262237348:web:d6edf104e889a931acd231',
    messagingSenderId: '604262237348',
    projectId: 'frontend-8de80',
    authDomain: 'frontend-8de80.firebaseapp.com',
    storageBucket: 'frontend-8de80.appspot.com',
    measurementId: 'G-0EM8R38NCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYxzqb23Ak3QZ07H9qp408wXUgVKJ9TqU',
    appId: '1:604262237348:android:6b6d471930f17c34acd231',
    messagingSenderId: '604262237348',
    projectId: 'frontend-8de80',
    storageBucket: 'frontend-8de80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTwW6SkJGhaNz1nqROz-vCsoATSpfJNyQ',
    appId: '1:604262237348:ios:08ee579775f2993eacd231',
    messagingSenderId: '604262237348',
    projectId: 'frontend-8de80',
    storageBucket: 'frontend-8de80.appspot.com',
    iosClientId: '604262237348-g6eeloafp7tg69jjh4j2t7fu728k8928.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTwW6SkJGhaNz1nqROz-vCsoATSpfJNyQ',
    appId: '1:604262237348:ios:539719439b78a428acd231',
    messagingSenderId: '604262237348',
    projectId: 'frontend-8de80',
    storageBucket: 'frontend-8de80.appspot.com',
    iosClientId: '604262237348-rgnsb6nk3n6dq7bh9hti5ef97g2q5bnu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth.RunnerTests',
  );
}
